### ISSUE TITLE
load_preproc_data_adult() raises not implemented error with pandas 1.0.0

### ISSUE THREAD

**Issue by Vaunorage** [IBM/AIF360#167] opened 2020-04-10 23:48 UTC
https://pandas.pydata.org/docs/whatsnew/v1.0.0.html :
The ‘outer’ method on Numpy ufuncs, e.g. np.subtract.outer operating on Series objects is no longer supported,

**Comment by adrinjalali** [comment] 2020-04-14 09:10
Thanks for reporting the issue. Could you please also include a [minimal and reproducible example](http://sscce.org/) for us to better diagnose the problem?

**Comment by hoffmansc** [comment] 2020-04-14 13:38
Duplicate of #162 and #109. The fix is in master as well as the latest rc version, v0.3.0rc0. You can download this from PyPI like: `pip install aif360==0.3.0rc0`

**Closed by hoffmansc** 2020-04-14 13:38 UTC
